# Generated by Django 4.0.3 on 2023-06-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_appointment_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
    ]
