# Generated by Django 4.0.3 on 2023-06-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_remove_automobilevo_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='auto_vin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automobiles', to='service_rest.automobilevo'),
        ),
    ]
