# Generated by Django 4.0.3 on 2023-06-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0013_appointment_auto_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='vin',
            new_name='auto_vin',
        ),
    ]
