# Generated by Django 4.0.3 on 2023-06-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0014_rename_vin_automobilevo_auto_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='auto_vin',
            new_name='vin',
        ),
    ]
