# Generated by Django 4.0.3 on 2023-06-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0015_rename_auto_vin_automobilevo_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='vin',
            new_name='auto_vin',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='auto_vin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vin', to='service_rest.automobilevo'),
        ),
    ]
