# Generated by Django 4.0.3 on 2023-06-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0017_rename_auto_vin_automobilevo_vin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='auto',
        ),
    ]
